apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deploy.name}}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.name }}
    spec:
      containers:
        - image: "{{ .Values.deploy.image }}:{{ .Values.deploy.imageTag }}"
          imagePullPolicy: Always
          name: {{ .Values.deploy.name }}
      restartPolicy: Always