apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.deploy.name}}"
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: postgresql-client
  template:
    metadata:
      labels:
        app: postgresql-client
    spec:
      containers:
        - image: "alpine:{{.Values.deploy.imageTag}}"
          imagePullPolicy: Always
          name: postgresql-client
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]     
      restartPolicy: Always